// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ITP2Tree.Data;

#nullable disable

namespace ITP2Tree.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ITP2Tree.Data.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("ITP2Tree.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Geburtsdatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geburtsort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verwandte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("ITP2Tree.Data.Verwandtschaft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beziehungstyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonAId");

                    b.HasIndex("PersonBId");

                    b.ToTable("Verwandtschaften");
                });

            modelBuilder.Entity("ITP2Tree.Data.Person", b =>
                {
                    b.HasOne("ITP2Tree.Data.Benutzer", "Benutzer")
                        .WithMany("Personen")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("ITP2Tree.Data.Verwandtschaft", b =>
                {
                    b.HasOne("ITP2Tree.Data.Person", "PersonA")
                        .WithMany("VerwandtschaftenAlsQuelle")
                        .HasForeignKey("PersonAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITP2Tree.Data.Person", "PersonB")
                        .WithMany("VerwandtschaftenAlsZiel")
                        .HasForeignKey("PersonBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonA");

                    b.Navigation("PersonB");
                });

            modelBuilder.Entity("ITP2Tree.Data.Benutzer", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("ITP2Tree.Data.Person", b =>
                {
                    b.Navigation("VerwandtschaftenAlsQuelle");

                    b.Navigation("VerwandtschaftenAlsZiel");
                });
#pragma warning restore 612, 618
        }
    }
}
